// swift-tools-version:5.9
import PackageDescription

// Dependency manifest for Apple-app-only Swift packages.
//
// The application project itself is generated by XcodeGen, so packages declared
// only in project.yml are invisible to Dependabot's Swift Package Manager
// updater. Keep the version here as the single source of truth; the XcodeGen
// wrapper reads this exact version when generating Bastion.xcodeproj.
let package = Package(
    name: "BastionAppDependencies",
    dependencies: [
        .package(
            url: "https://github.com/migueldeicaza/SwiftTerm.git",
            exact: "1.18.0"
        ),
    ]
)
