name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read

jobs:
  dotnet:
    uses: Avkroken/.github/.github/workflows/dotnet.yml@5f094ef8cf6348784f5b68f3fb3ffc4cda7f5929
    with:
      dotnet_version: 10.0.x
      test_working_directory: WindowsApp/Bastion.Core.Tests
      application_project: WindowsApp/WindowsApp.csproj
      install_openssh: true
