name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: write

jobs:
  gradle:
    uses: Avkroken/.github/.github/workflows/gradle.yml@5f094ef8cf6348784f5b68f3fb3ffc4cda7f5929
    with:
      working_directory: Android
      java_version: '17'
      dependency_submission: true
      dependency_projects: ':app'
      dependency_configurations: '.*[Rr]untimeClasspath'
