name: Swift Linux

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  swift-linux:
    name: CI / swift-linux
    runs-on: ${{ (github.event_name == 'merge_group' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)) && 'ubuntu-latest' || 'mp100-linux' }}
    container: swift:6.1-noble
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: |
          apt-get update -qq
          apt-get install -y -qq zip unzip
          swift build
          swift test
