name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read

jobs:
  swift:
    uses: Avkroken/.github/.github/workflows/swift.yml@5f094ef8cf6348784f5b68f3fb3ffc4cda7f5929
    with:
      package_path: .
