name: Windows

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq openssh-server openssh-client
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - run: dotnet test WindowsApp/Bastion.Core.Tests/Bastion.Core.Tests.csproj -c Release

  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - run: dotnet build WindowsApp/WindowsApp.csproj -c Release -p:Platform=x64

  windows:
    name: CI / windows
    if: always()
    needs: [core-tests, build]
    runs-on: ubuntu-latest
    steps:
      - run: |
          test "${{ needs.core-tests.result }}" = success
          test "${{ needs.build.result }}" = success
